var tree = [["Stampie","Stampie.html","",
                [["Adapter","Stampie\/Adapter.html","",
                [["AdapterInterface","Stampie\/Adapter\/AdapterInterface.html","",
                [        ]],["Buzz","Stampie\/Adapter\/Buzz.html","",
                [        ]],["Guzzle","Stampie\/Adapter\/Guzzle.html","",
                [        ]],["Response","Stampie\/Adapter\/Response.html","",
                [        ]],["ResponseInterface","Stampie\/Adapter\/ResponseInterface.html","",
                [        ]]        ]],["Exception","Stampie\/Exception.html","",
                [["ApiException","Stampie\/Exception\/ApiException.html"," < RuntimeException",
                [        ]],["HttpException","Stampie\/Exception\/HttpException.html"," < RuntimeException",
                [        ]]        ]],["Mailer","Stampie\/Mailer.html","",
                [["Postmark","Stampie\/Mailer\/Postmark.html"," < Mailer",
                [        ]],["SendGrid","Stampie\/Mailer\/SendGrid.html"," < Mailer",
                [        ]]        ]],["Mailer","Stampie\/Mailer.html","",
                [        ]],["MailerInterface","Stampie\/MailerInterface.html","",
                [        ]],["Message","Stampie\/Message.html","",
                [        ]],["MessageInterface","Stampie\/MessageInterface.html","",
                [        ]],["Version","Stampie\/Version.html","",
                [        ]]        ]]        ]

