var tree = [["Stampie","Stampie.html","",
                [["Adapter","Stampie\/Adapter.html","",
                [["AdapterInterface","Stampie\/Adapter\/AdapterInterface.html","",
                [        ]],["Buzz","Stampie\/Adapter\/Buzz.html","",
                [        ]],["Guzzle","Stampie\/Adapter\/Guzzle.html","",
                [        ]],["NoopAdapter","Stampie\/Adapter\/NoopAdapter.html","",
                [        ]],["Response","Stampie\/Adapter\/Response.html","",
                [        ]],["ResponseInterface","Stampie\/Adapter\/ResponseInterface.html","",
                [        ]]        ]],["Exception","Stampie\/Exception.html","",
                [["ApiException","Stampie\/Exception\/ApiException.html"," < RuntimeException",
                [        ]],["HttpException","Stampie\/Exception\/HttpException.html"," < RuntimeException",
                [        ]]        ]],["Mailer","Stampie\/Mailer.html","",
                [["MailChimpSts","Stampie\/Mailer\/MailChimpSts.html"," < Mailer",
                [        ]],["MailGun","Stampie\/Mailer\/MailGun.html"," < Mailer",
                [        ]],["Mandrill","Stampie\/Mailer\/Mandrill.html"," < Mailer",
                [        ]],["Postmark","Stampie\/Mailer\/Postmark.html"," < Mailer",
                [        ]],["SendGrid","Stampie\/Mailer\/SendGrid.html"," < Mailer",
                [        ]]        ]],["Message","Stampie\/Message.html","",
                [["TaggableInterface","Stampie\/Message\/TaggableInterface.html","",
                [        ]]        ]],["Util","Stampie\/Util.html","",
                [["IdentityUtils","Stampie\/Util\/IdentityUtils.html","",
                [        ]]        ]],["Identity","Stampie\/Identity.html","",
                [        ]],["IdentityInterface","Stampie\/IdentityInterface.html","",
                [        ]],["Mailer","Stampie\/Mailer.html","",
                [        ]],["MailerInterface","Stampie\/MailerInterface.html","",
                [        ]],["Message","Stampie\/Message.html","",
                [        ]],["MessageInterface","Stampie\/MessageInterface.html","",
                [        ]]        ]]        ]

